// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nao1215/emigre/server/app/interactor"
	"github.com/nao1215/emigre/server/app/usecase"
)

// Injectors from wire.go:

// NewEmigre returns a new Emigre struct.
func NewEmigre() (*Emigre, error) {
	userCreator := interactor.NewUserCreator()
	emigre := newEmigre(userCreator)
	return emigre, nil
}

// wire.go:

// Emigre is a struct that contains the settings for the Emigre.
type Emigre struct {
	// UserCreator is an interactor for creating users.
	UserCreator usecase.UserCreator
}

// newEmigre returns a new Emigre struct.
func newEmigre(
	uc usecase.UserCreator,
) *Emigre {
	return &Emigre{
		UserCreator: uc,
	}
}
