version: 2
updates:
  - package-ecosystem: gomod
    directory: "server/"
    schedule:
      interval: daily
      time: "20:00"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "client/"
    schedule:
      interval: daily
      time: "20:00"
    open-pull-requests-limit: 10
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
