// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nao1215/emigre/server/app/interactor"
	"github.com/nao1215/emigre/server/app/usecase"
)

// Injectors from wire.go:

// NewEmigre returns a new Emigre struct.
func NewEmigre() *Emigre {
	userCreator := interactor.NewUserCreator()
	emigre := newEmigre(userCreator)
	return emigre
}

// wire.go:

// Emigre is a struct that contains the settings for the Emigre.
type Emigre struct {
	User *User
}

// User is a struct that contains the settings for the user.
type User struct {
	// Creator is an usecase for creating users.
	Creator usecase.UserCreator
}

// newEmigre returns a new Emigre struct.
func newEmigre(
	uc usecase.UserCreator,
) *Emigre {
	return &Emigre{
		User: &User{
			Creator: uc,
		},
	}
}
