definitions:
  api.HealthResponse:
    properties:
      name:
        description: '@Description Name is server name.'
        type: string
      revision:
        description: '@Description Revision is git revision'
        type: string
      version:
        description: '@Description Version is repository tag version'
        type: string
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      description: This API is for checking server health. The api return server name,
        version and revision.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.HealthResponse'
      summary: Get server health information
swagger: "2.0"
